name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'   # Kích hoạt workflow khi có push tag bắt đầu với chữ 'v', ví dụ: v1.0.0
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Clean cache
        run: rm -rf node_modules package-lock.json release

      - name: Install Wine for Electron Builder
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32
      
      - name: Install additional libraries
        run: |
          sudo apt install -y xvfb g++-multilib gcc-multilib

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Package Electron app
        run: npm run electron-build

      - name: List files in release directory
        run: ls -la release

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.exe
            release/*.deb
            release/*.yml
            release/*.AppImage

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
