name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'   # Kích hoạt workflow khi có push tag bắt đầu với chữ 'v', ví dụ: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Package Electron app
        run: npm run build-prod

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: electron/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
